### ISSUE TITLE
When Open error occured

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Bibliofile/iphone-backup-browser#2]
```
this good developed tool by someone... i do not know who is this 
but have some issue when open exe here i attach screen shot for that.
kindly pleas help out for that 
```

Original issue reported on code.google.com by `Ashishda...@gmail.com` on 1 Nov 2013 at 4:11

Attachments:
- [iphone backup.jpg](https://storage.googleapis.com/google-code-attachments/iphone-backup-browser/issue-2/comment-0/iphone backup.jpg)

**Comment by Bibliofile** [comment]
Closing... deals with a release which will not be supported, and the issue was likely that the zip wasn't unpacked.
